# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df8a3a7c4077bfd1ca6dc4cf06943ab012591f861fc357c17fad5cdc0c78a0459a53c76ceb666faca846b5487108b991ed795b32afa146d73e6d7451d8d54997

test:
  secret_key_base: 2c1fc392cbf501ce45e72fe7039f89b76e9d477db1dc777ee8434bcb767ddb108e881133461b8ef004f523eef18a7c54e885767b0261fda10f3ac2993c85033d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
